version: "3.7"
services:
  web:
    build: .
    ports:
      - "9090:9090"
    networks:
      ncnewsnetwork:
    environment:
      DB_HOST: db
      DB_USER: username
      DB_NAME: ncnews
      DB_PASSWORD: password
      DB_PORT: 5432
      DB_URL: postgres://username:password@db:5432/ncnews
    depends_on:
      - db
  db:
    image: postgres
    networks:
      - ncnewsnetwork
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ncnews
      POSTGRES_PASSWORD: password
      POSTGRES_USER: username
volumes:
  pgdata:
networks:
  ncnewsnetwork:
